inputs:
  - path: /log/app-error.json
    type: socket
    tags:
      - name: hostname
        value: $HOSTNAME
      - name: event_type
        value: php.app-errors
      - name: team
        value: $TEAM
      - name: application
        value: $APPLICATION

  - path: /log/app-access.json
    type: pipe
    tags:
      - name: hostname
        value: $HOSTNAME
      - name: event_type
        value: php.app-access
      - name: team
        value: $TEAM
      - name: application
        value: $APPLICATION

  - path: /log/php-error.log
    type: pipe
    multiline:
      enabled: true
      first_line: ^\[\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2}\s+.*\] PHP (Notice|Fatal)
      flush_interval: 2
    parsers:
      - ^\[(?P<time>\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2}\s\w+\/\w+)\] PHP (?P<severity>[^:]+):(\s+)?(?P<msg>.*)
    tags:
      - name: hostname
        value: $HOSTNAME
      - name: event_type
        value: php.error
      - name: team
        value: $TEAM
      - name: application
        value: $APPLICATION

  - path: /log/fpm-error.log
    type: pipe
    multiline:
      enabled: true
      first_line: ^\[\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2}(.?\d+)?\]
      flush_interval: 2
    parsers:
      - ^\[(?P<timestamp>\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2}(.?\d+)?)\] (?P<msg>.*)
    tags:
      - name: hostname
        value: $HOSTNAME
      - name: event_type
        value: php.fpm-error
      - name: team
        value: $TEAM
      - name: application
        value: $APPLICATION

  - path: /log/slow.log
    type: pipe
    multiline:
      enabled: true
      first_line: ^\[(\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2})(\.\d{6})?\]
      flush_interval: 2
    parsers:
      - ^\[(?P<time>\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2}(\.\d{6})?)\]\s+\[pool\s+(?P<pool>\w+)\]\s+pid\s+(?P<pid>\d+)\s?(?P<msg>.*)
    tags:
      - name: hostname
        value: $HOSTNAME
      - name: event_type
        value: php.slowlog
      - name: team
        value: $TEAM
      - name: application
        value: $APPLICATION
