inputs:
  - path: "/tmp/123"
    tags:
      - name: "tag1"
        value: "value1"
    multiline:
      enabled: false
  - path: "/tmp/321"
    tags:
      - name: "tag1"
        value: "value1"
    multiline:
      enabled: true
      first_line: ^\[\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2}\]
    parsers:
      - ^\[(?P<time>\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2})\]\s+\[pool\s+(?P<pool>\w+)\]\s+pid\s+(?P<pid>\d+)\s?(?P<msg>.*)

